langage: node_js
node_js:
  - "12.13.0"
git:
  depth: 1

install: yarn

script: yarn build

env:
  global:
    secure: hash value

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master