langage: node_js
node_js:
  - "12.13.0"
git:
  depth: 1

install: yarn

script: yarn build

after_success:
  - cd ./dist
  - rm -rf .git
  - git init
  - git config --global user.name "annder"
  - git config --global user.email "2461067798@qq.com"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --quiet --force  "https://github.com/annder/vue-flow-line/tree/gh-pages" master:gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $ci # Set in travis-ci.org dashboard
  on:
    branch: master
